
Updating the Charts....
['Electron Beam Powder Bed Fusion', 'Area-wise Laser Beam Powder Bed Fusion', 'Laser Powder Bed Fusion', 'Powder Laser Energy Deposition', 'Cold Spray', 'Wire Electric Arc Energy Deposition', 'Wire Plasma Arc Energy Deposition', 'Wire Laser Energy Deposition', 'Wire Electron Beam Energy Deposition', 'Liquid Metal Printing', 'Friction Energy Deposition', 'Other Metal', 'Material Jetting', 'Mold Slurry Deposition', 'Area-wise Vat Polymerisation', 'Dispersion Material Extrusion', 'Filament Material Extrusion', 'Pellet Material Extrusion', 'Machined Binder Jetting', 'Binder Jetting', 'Metal Selective Laser Sintering']
Sorted Feedstock chart data for Metal: {'Powder': 8, 'Wire': 5, 'Rods': 1, 'Other': 1, 'Dispersion': 4, 'Filament': 1, 'Pellets': 1}
Feedstock-Process chart data: {'Direct - Powder': 4, 'Direct - Wire': 5, 'Direct - Rods': 1, 'Direct - Other': 1, 'Sinter-based - Dispersion': 4, 'Sinter-based - Filament': 1, 'Sinter-based - Pellets': 1, 'Sinter-based - Powder': 3}
Creating the presentation.... 

Image for Dispersion Material Extrusion not found. Using a default image.
Image for Pellet Material Extrusion not found. Using a default image.
Traceback (most recent call last):
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\serialized.py", line 81, in _write
    self._write_content_types_stream(phys_writer)
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\serialized.py", line 91, in _write_content_types_stream
    phys_writer.write(
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\serialized.py", line 220, in write
    self._zipf.writestr(pack_uri.membername, blob)
    ^^^^^^^^^^
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\util.py", line 215, in __get__
    value = self._fget(obj)
            ^^^^^^^^^^^^^^^
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\serialized.py", line 225, in _zipf
    return zipfile.ZipFile(self._pkg_file, "w", compression=zipfile.ZIP_DEFLATED)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\zipfile.py", line 1284, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'Map Output\\Metal Map Round 2023-11-26_21-48.pptx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HZitu\ampower\Staff - Dokumente\Zitu\Map Master\AMbase Plugin - Technology Maps\ambase2\plugins\technology_maps\technology_maps.py", line 58, in <module>
    main(material)
  File "C:\Users\HZitu\ampower\Staff - Dokumente\Zitu\Map Master\AMbase Plugin - Technology Maps\ambase2\plugins\technology_maps\technology_maps.py", line 46, in main
    map.prs.save(output_path)
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\presentation.py", line 39, in save
    self.part.save(file)
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\parts\presentation.py", line 107, in save
    self.package.save(path_or_stream)
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\package.py", line 153, in save
    PackageWriter.write(pkg_file, self._rels, tuple(self.iter_parts()))
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\serialized.py", line 76, in write
    cls(pkg_file, pkg_rels, parts)._write()
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\serialized.py", line 80, in _write
    with _PhysPkgWriter.factory(self._pkg_file) as phys_writer:
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\serialized.py", line 216, in __exit__
    self._zipf.close()
    ^^^^^^^^^^
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\util.py", line 215, in __get__
    value = self._fget(obj)
            ^^^^^^^^^^^^^^^
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pptx\opc\serialized.py", line 225, in _zipf
    return zipfile.ZipFile(self._pkg_file, "w", compression=zipfile.ZIP_DEFLATED)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HZitu\AppData\Local\Programs\Python\Python311\Lib\zipfile.py", line 1284, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'Map Output\\Metal Map Round 2023-11-26_21-48.pptx'
